[program:forum_app]
command=/var/www/forum_app/env/bin/gunicorn forum_app.wsgi:application -c /var/www/forum_app/gunicorn.conf.py
directory=/var/www/forum_app
user=www-data
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/var/log/supervisor/forum_app.log
stderr_logfile=/var/log/supervisor/forum_app_err.log
environment=LANG=en_US.UTF-8,LC_ALL=en_US.UTF-8
